/* ============================================================
   Thaï — palier A1 (Débutant)
   Chaque entrée : écriture thaïe, romanisation avec tons,
   glose française, glose anglaise, emoji.
   ============================================================ */
ajouterPalier({
  palier:'a1',
  tonsNoms:{ fr:['moyen','bas','descendant','haut','montant'],
             en:['mid','low','falling','high','rising'] },

  lexique:{
  /* — salutations et politesse — */
  sawatdee:{ th:'สวัสดี', rom:'sà-wàt-dii', fr:'bonjour', en:'hello', emoji:'👋' },
  khrap:{ th:'ครับ', rom:'khráp', fr:'(politesse, homme)', en:'(polite, male)', emoji:'🙋‍♂️' },
  kha:{ th:'ค่ะ', rom:'khâ', fr:'(politesse, femme)', en:'(polite, female)', emoji:'🙋‍♀️' },
  khopkhun:{ th:'ขอบคุณ', rom:'khɔ̀ɔp-khun', fr:'merci', en:'thank you', emoji:'🙏' },
  khothot:{ th:'ขอโทษ', rom:'khɔ̌ɔ-thôot', fr:'pardon', en:'sorry', emoji:'😅' },
  chai:{ th:'ใช่', rom:'châi', fr:'oui', en:'yes', emoji:'✅' },
  mai_no:{ th:'ไม่', rom:'mâi', fr:'non / ne pas', en:'no / not', emoji:'❌' },
  sabaidee:{ th:'สบายดี', rom:'sà-baai-dii', fr:'ça va bien', en:'I’m fine', emoji:'😊' },
  lakon:{ th:'ลาก่อน', rom:'laa-kɔ̀ɔn', fr:'au revoir', en:'goodbye', emoji:'👋' },
  yindee:{ th:'ยินดี', rom:'yin-dii', fr:'enchanté', en:'delighted', emoji:'🤝' },
  maipenrai:{ th:'ไม่เป็นไร', rom:'mâi-pen-rai', fr:'de rien / pas grave', en:'no worries', emoji:'🤷' },
  chok_dee:{ th:'โชคดี', rom:'chôok-dii', fr:'bonne chance', en:'good luck', emoji:'🍀' },
  raatri:{ th:'ราตรีสวัสดิ์', rom:'raa-trii-sà-wàt', fr:'bonne nuit', en:'good night', emoji:'🌙' },
  phop_kan:{ th:'แล้วเจอกัน', rom:'lɛ́ɛo jəə kan', fr:'à bientôt', en:'see you soon', emoji:'👋' },

  /* — personnes et pronoms — */
  phom:{ th:'ผม', rom:'phǒm', fr:'je (homme)', en:'I (male)', emoji:'👨' },
  chan:{ th:'ฉัน', rom:'chǎn', fr:'je (femme)', en:'I (female)', emoji:'👩' },
  khun:{ th:'คุณ', rom:'khun', fr:'tu / vous', en:'you', emoji:'🫵' },
  khao:{ th:'เขา', rom:'khǎo', fr:'il / elle', en:'he / she', emoji:'🧑' },
  rao:{ th:'เรา', rom:'rao', fr:'nous', en:'we', emoji:'👨‍👩‍👧' },
  phuak_khao:{ th:'พวกเขา', rom:'phûak-khǎo', fr:'ils / elles', en:'they', emoji:'👥' },
  khon:{ th:'คน', rom:'khon', fr:'personne', en:'person', emoji:'🧍' },
  phuean:{ th:'เพื่อน', rom:'phûean', fr:'ami', en:'friend', emoji:'👯' },
  khru:{ th:'ครู', rom:'khruu', fr:'professeur', en:'teacher', emoji:'👩‍🏫' },
  nakrian:{ th:'นักเรียน', rom:'nák-rian', fr:'élève', en:'student', emoji:'🎒' },
  cheu:{ th:'ชื่อ', rom:'chûue', fr:'nom / s’appeler', en:'name / to be called', emoji:'🏷️' },
  arai:{ th:'อะไร', rom:'à-rai', fr:'quoi', en:'what', emoji:'❓' },
  phuchai:{ th:'ผู้ชาย', rom:'phûu-chaai', fr:'homme', en:'man', emoji:'👨' },
  phuying:{ th:'ผู้หญิง', rom:'phûu-yǐng', fr:'femme', en:'woman', emoji:'👩' },
  dek:{ th:'เด็ก', rom:'dèk', fr:'enfant', en:'child', emoji:'🧒' },

  /* — famille — */
  mae:{ th:'แม่', rom:'mɛ̂ɛ', fr:'mère', en:'mother', emoji:'👩' },
  pho:{ th:'พ่อ', rom:'phɔ̂ɔ', fr:'père', en:'father', emoji:'👨' },
  luk:{ th:'ลูก', rom:'lûuk', fr:'enfant (fils/fille)', en:'child (offspring)', emoji:'👶' },
  phi:{ th:'พี่', rom:'phîi', fr:'aîné(e)', en:'older sibling', emoji:'🧑' },
  nong:{ th:'น้อง', rom:'nɔ́ɔng', fr:'cadet(te)', en:'younger sibling', emoji:'🧒' },
  khropkhrua:{ th:'ครอบครัว', rom:'khrɔ̂ɔp-khrua', fr:'famille', en:'family', emoji:'👨‍👩‍👧' },
  pu:{ th:'ปู่', rom:'pùu', fr:'grand-père paternel', en:'paternal grandfather', emoji:'👴' },
  ya:{ th:'ย่า', rom:'yâa', fr:'grand-mère paternelle', en:'paternal grandmother', emoji:'👵' },
  ta:{ th:'ตา', rom:'taa', fr:'grand-père maternel', en:'maternal grandfather', emoji:'👴' },
  yai:{ th:'ยาย', rom:'yaai', fr:'grand-mère maternelle', en:'maternal grandmother', emoji:'👵' },
  sami:{ th:'สามี', rom:'sǎa-mii', fr:'mari', en:'husband', emoji:'🤵' },
  phanraya:{ th:'ภรรยา', rom:'phan-rá-yaa', fr:'épouse', en:'wife', emoji:'👰' },

  /* — nombres — */
  sun:{ th:'ศูนย์', rom:'sǔun', fr:'zéro', en:'zero', emoji:'0️⃣' },
  nueng:{ th:'หนึ่ง', rom:'nùeng', fr:'un', en:'one', emoji:'1️⃣' },
  song:{ th:'สอง', rom:'sɔ̌ɔng', fr:'deux', en:'two', emoji:'2️⃣' },
  sam:{ th:'สาม', rom:'sǎam', fr:'trois', en:'three', emoji:'3️⃣' },
  si:{ th:'สี่', rom:'sìi', fr:'quatre', en:'four', emoji:'4️⃣' },
  ha:{ th:'ห้า', rom:'hâa', fr:'cinq', en:'five', emoji:'5️⃣' },
  hok:{ th:'หก', rom:'hòk', fr:'six', en:'six', emoji:'6️⃣' },
  jet:{ th:'เจ็ด', rom:'jèt', fr:'sept', en:'seven', emoji:'7️⃣' },
  paet:{ th:'แปด', rom:'pɛ̀ɛt', fr:'huit', en:'eight', emoji:'8️⃣' },
  kao:{ th:'เก้า', rom:'kâao', fr:'neuf', en:'nine', emoji:'9️⃣' },
  sip:{ th:'สิบ', rom:'sìp', fr:'dix', en:'ten', emoji:'🔟' },
  sip_et:{ th:'สิบเอ็ด', rom:'sìp-èt', fr:'onze', en:'eleven', emoji:'1️⃣' },
  yisip:{ th:'ยี่สิบ', rom:'yîi-sìp', fr:'vingt', en:'twenty', emoji:'2️⃣' },
  roi:{ th:'ร้อย', rom:'rɔ́ɔi', fr:'cent', en:'hundred', emoji:'💯' },
  phan:{ th:'พัน', rom:'phan', fr:'mille', en:'thousand', emoji:'🔢' },
  baht:{ th:'บาท', rom:'bàat', fr:'baht', en:'baht', emoji:'💰' },
  thaorai:{ th:'เท่าไหร่', rom:'thâo-rài', fr:'combien', en:'how much', emoji:'🧮' },
  ki:{ th:'กี่', rom:'kìi', fr:'combien de', en:'how many', emoji:'🔢' },

  /* — nourriture et boissons — */
  nam:{ th:'น้ำ', rom:'náam', fr:'eau', en:'water', emoji:'💧' },
  khao_rice:{ th:'ข้าว', rom:'khâao', fr:'riz', en:'rice', emoji:'🍚' },
  kafae:{ th:'กาแฟ', rom:'kaa-fɛɛ', fr:'café', en:'coffee', emoji:'☕' },
  cha:{ th:'ชา', rom:'chaa', fr:'thé', en:'tea', emoji:'🍵' },
  ahan:{ th:'อาหาร', rom:'aa-hǎan', fr:'nourriture', en:'food', emoji:'🍽️' },
  phonlamai:{ th:'ผลไม้', rom:'phǒn-lá-máai', fr:'fruit', en:'fruit', emoji:'🍍' },
  kai:{ th:'ไก่', rom:'kài', fr:'poulet', en:'chicken', emoji:'🍗' },
  mu:{ th:'หมู', rom:'mǔu', fr:'porc', en:'pork', emoji:'🐷' },
  nuea:{ th:'เนื้อ', rom:'núea', fr:'bœuf / viande', en:'beef / meat', emoji:'🥩' },
  pla:{ th:'ปลา', rom:'plaa', fr:'poisson', en:'fish', emoji:'🐟' },
  kung:{ th:'กุ้ง', rom:'kûng', fr:'crevette', en:'shrimp', emoji:'🦐' },
  phak:{ th:'ผัก', rom:'phàk', fr:'légume', en:'vegetable', emoji:'🥬' },
  khai:{ th:'ไข่', rom:'khài', fr:'œuf', en:'egg', emoji:'🥚' },
  namtan:{ th:'น้ำตาล', rom:'nám-taan', fr:'sucre', en:'sugar', emoji:'🍬' },
  kluea:{ th:'เกลือ', rom:'klʉa', fr:'sel', en:'salt', emoji:'🧂' },
  phet:{ th:'เผ็ด', rom:'phèt', fr:'épicé', en:'spicy', emoji:'🌶️' },
  aroi:{ th:'อร่อย', rom:'à-rɔ̀i', fr:'délicieux', en:'delicious', emoji:'😋' },
  wan:{ th:'หวาน', rom:'wǎan', fr:'sucré', en:'sweet', emoji:'🍯' },
  priao:{ th:'เปรี้ยว', rom:'prîao', fr:'acide', en:'sour', emoji:'🍋' },
  khem:{ th:'เค็ม', rom:'khem', fr:'salé', en:'salty', emoji:'🧂' },
  kuaitiao:{ th:'ก๋วยเตี๋ยว', rom:'kǔai-tǐao', fr:'soupe de nouilles', en:'noodle soup', emoji:'🍜' },
  phatthai:{ th:'ผัดไทย', rom:'phàt-thai', fr:'pad thaï', en:'pad thai', emoji:'🍤' },
  somtam:{ th:'ส้มตำ', rom:'sôm-tam', fr:'salade de papaye', en:'papaya salad', emoji:'🥗' },
  bia:{ th:'เบียร์', rom:'bia', fr:'bière', en:'beer', emoji:'🍺' },
  namkhaeng:{ th:'น้ำแข็ง', rom:'náam-khǎeng', fr:'glaçons', en:'ice', emoji:'🧊' },
  nom:{ th:'นม', rom:'nom', fr:'lait', en:'milk', emoji:'🥛' },
  khanom:{ th:'ขนม', rom:'khà-nǒm', fr:'friandise', en:'snack', emoji:'🍪' },
  hiu:{ th:'หิว', rom:'hǐu', fr:'avoir faim', en:'to be hungry', emoji:'😋' },
  im:{ th:'อิ่ม', rom:'ìm', fr:'être rassasié', en:'to be full', emoji:'😌' },

  /* — verbes du quotidien — */
  kin:{ th:'กิน', rom:'kin', fr:'manger', en:'to eat', emoji:'🍴' },
  duem:{ th:'ดื่ม', rom:'dùuem', fr:'boire', en:'to drink', emoji:'🥤' },
  pai:{ th:'ไป', rom:'pai', fr:'aller', en:'to go', emoji:'🚶' },
  ma:{ th:'มา', rom:'maa', fr:'venir', en:'to come', emoji:'🔙' },
  chop:{ th:'ชอบ', rom:'chɔ̂ɔp', fr:'aimer bien', en:'to like', emoji:'👍' },
  rak:{ th:'รัก', rom:'rák', fr:'aimer (d’amour)', en:'to love', emoji:'❤️' },
  mi:{ th:'มี', rom:'mii', fr:'avoir', en:'to have', emoji:'🎁' },
  pen:{ th:'เป็น', rom:'pen', fr:'être (identité)', en:'to be (identity)', emoji:'🪪' },
  yu:{ th:'อยู่', rom:'yùu', fr:'être (situé)', en:'to be (located)', emoji:'📍' },
  phut:{ th:'พูด', rom:'phûut', fr:'parler', en:'to speak', emoji:'💬' },
  ao:{ th:'เอา', rom:'ao', fr:'prendre / vouloir', en:'to take / want', emoji:'🤲' },
  yak:{ th:'อยาก', rom:'yàak', fr:'vouloir', en:'to want to', emoji:'🌟' },
  tham:{ th:'ทำ', rom:'tham', fr:'faire', en:'to do / make', emoji:'🔨' },
  du:{ th:'ดู', rom:'duu', fr:'regarder', en:'to watch', emoji:'👀' },
  fang:{ th:'ฟัง', rom:'fang', fr:'écouter', en:'to listen', emoji:'👂' },
  an:{ th:'อ่าน', rom:'àan', fr:'lire', en:'to read', emoji:'📖' },
  khian:{ th:'เขียน', rom:'khǐan', fr:'écrire', en:'to write', emoji:'✍️' },
  non:{ th:'นอน', rom:'nɔɔn', fr:'dormir', en:'to sleep', emoji:'😴' },
  thamngan:{ th:'ทำงาน', rom:'tham-ngaan', fr:'travailler', en:'to work', emoji:'💼' },
  rian:{ th:'เรียน', rom:'rian', fr:'étudier', en:'to study', emoji:'🎓' },
  sue:{ th:'ซื้อ', rom:'súue', fr:'acheter', en:'to buy', emoji:'🛒' },
  khai_sell:{ th:'ขาย', rom:'khǎai', fr:'vendre', en:'to sell', emoji:'🏪' },
  hai:{ th:'ให้', rom:'hâi', fr:'donner', en:'to give', emoji:'🎁' },
  ru:{ th:'รู้', rom:'rúu', fr:'savoir', en:'to know', emoji:'💡' },
  khaochai:{ th:'เข้าใจ', rom:'khâo-jai', fr:'comprendre', en:'to understand', emoji:'💭' },
  chuai:{ th:'ช่วย', rom:'chûai', fr:'aider', en:'to help', emoji:'🆘' },
  ro:{ th:'รอ', rom:'rɔɔ', fr:'attendre', en:'to wait', emoji:'⏳' },
  doen:{ th:'เดิน', rom:'dəən', fr:'marcher', en:'to walk', emoji:'🚶' },
  wing:{ th:'วิ่ง', rom:'wîng', fr:'courir', en:'to run', emoji:'🏃' },
  nang:{ th:'นั่ง', rom:'nâng', fr:'s’asseoir', en:'to sit', emoji:'🪑' },
  yuen:{ th:'ยืน', rom:'yʉʉn', fr:'se tenir debout', en:'to stand', emoji:'🧍' },

  /* — couleurs et qualificatifs — */
  si_daeng:{ th:'สีแดง', rom:'sǐi-dɛɛng', fr:'rouge', en:'red', emoji:'🔴' },
  si_namngen:{ th:'สีน้ำเงิน', rom:'sǐi-náam-ngəən', fr:'bleu', en:'blue', emoji:'🔵' },
  si_khiao:{ th:'สีเขียว', rom:'sǐi-khǐao', fr:'vert', en:'green', emoji:'🟢' },
  si_dam:{ th:'สีดำ', rom:'sǐi-dam', fr:'noir', en:'black', emoji:'⚫' },
  si_khao:{ th:'สีขาว', rom:'sǐi-khǎao', fr:'blanc', en:'white', emoji:'⚪' },
  si_lueang:{ th:'สีเหลือง', rom:'sǐi-lʉ̌ang', fr:'jaune', en:'yellow', emoji:'🟡' },
  si_som:{ th:'สีส้ม', rom:'sǐi-sôm', fr:'orange', en:'orange', emoji:'🟠' },
  yai:{ th:'ใหญ่', rom:'yài', fr:'grand', en:'big', emoji:'🐘' },
  lek:{ th:'เล็ก', rom:'lék', fr:'petit', en:'small', emoji:'🐜' },
  ron:{ th:'ร้อน', rom:'rɔ́ɔn', fr:'chaud', en:'hot', emoji:'🔥' },
  yen:{ th:'เย็น', rom:'yen', fr:'frais', en:'cool', emoji:'❄️' },
  nao:{ th:'หนาว', rom:'nǎao', fr:'froid (climat)', en:'cold (weather)', emoji:'🥶' },
  suai:{ th:'สวย', rom:'sǔai', fr:'joli', en:'beautiful', emoji:'🌸' },
  di:{ th:'ดี', rom:'dii', fr:'bien / bon', en:'good', emoji:'👌' },
  mai_di:{ th:'ไม่ดี', rom:'mâi-dii', fr:'mauvais', en:'bad', emoji:'👎' },
  phaeng:{ th:'แพง', rom:'phɛɛng', fr:'cher', en:'expensive', emoji:'💸' },
  thuk:{ th:'ถูก', rom:'thùuk', fr:'pas cher', en:'cheap', emoji:'🏷️' },
  mai_new:{ th:'ใหม่', rom:'mài', fr:'neuf / nouveau', en:'new', emoji:'✨' },
  kao_old:{ th:'เก่า', rom:'kào', fr:'vieux (chose)', en:'old (thing)', emoji:'📻' },
  reo:{ th:'เร็ว', rom:'reo', fr:'rapide', en:'fast', emoji:'⚡' },
  cha_slow:{ th:'ช้า', rom:'cháa', fr:'lent', en:'slow', emoji:'🐢' },
  mak:{ th:'มาก', rom:'mâak', fr:'beaucoup / très', en:'very / a lot', emoji:'📈' },
  nitnoi:{ th:'นิดหน่อย', rom:'nít-nɔ̀i', fr:'un peu', en:'a little', emoji:'🤏' },

  /* — temps — */
  wanni:{ th:'วันนี้', rom:'wan-níi', fr:'aujourd’hui', en:'today', emoji:'📅' },
  phrungni:{ th:'พรุ่งนี้', rom:'phrûng-níi', fr:'demain', en:'tomorrow', emoji:'⏭️' },
  mueawan:{ th:'เมื่อวาน', rom:'mûea-waan', fr:'hier', en:'yesterday', emoji:'⏮️' },
  tonchao:{ th:'ตอนเช้า', rom:'tɔɔn-cháao', fr:'le matin', en:'in the morning', emoji:'🌅' },
  tonbai:{ th:'ตอนบ่าย', rom:'tɔɔn-bàai', fr:'l’après-midi', en:'in the afternoon', emoji:'🌤️' },
  tonyen:{ th:'ตอนเย็น', rom:'tɔɔn-yen', fr:'le soir', en:'in the evening', emoji:'🌆' },
  klangkhuen:{ th:'กลางคืน', rom:'klaang-khʉʉn', fr:'la nuit', en:'at night', emoji:'🌙' },
  wela:{ th:'เวลา', rom:'wee-laa', fr:'temps / heure', en:'time', emoji:'⏰' },
  wan_day:{ th:'วัน', rom:'wan', fr:'jour', en:'day', emoji:'📆' },
  athit:{ th:'อาทิตย์', rom:'aa-thít', fr:'semaine', en:'week', emoji:'🗓️' },
  duean:{ th:'เดือน', rom:'dʉan', fr:'mois', en:'month', emoji:'🌛' },
  pi:{ th:'ปี', rom:'pii', fr:'année', en:'year', emoji:'🎊' },
  chaomong:{ th:'โมง', rom:'moong', fr:'heure (horloge)', en:'o’clock', emoji:'🕐' },
  diao_ni:{ th:'ตอนนี้', rom:'tɔɔn-níi', fr:'maintenant', en:'now', emoji:'⏱️' },

  /* — lieux et déplacements — */
  ban:{ th:'บ้าน', rom:'bâan', fr:'maison', en:'house', emoji:'🏠' },
  rot:{ th:'รถ', rom:'rót', fr:'voiture', en:'car', emoji:'🚗' },
  rotfai:{ th:'รถไฟ', rom:'rót-fai', fr:'train', en:'train', emoji:'🚆' },
  rotmee:{ th:'รถเมล์', rom:'rót-mee', fr:'bus', en:'bus', emoji:'🚌' },
  taxi:{ th:'แท็กซี่', rom:'thɛ́k-sîi', fr:'taxi', en:'taxi', emoji:'🚕' },
  khrueangbin:{ th:'เครื่องบิน', rom:'khrûeang-bin', fr:'avion', en:'plane', emoji:'✈️' },
  rongraem:{ th:'โรงแรม', rom:'roong-rɛɛm', fr:'hôtel', en:'hotel', emoji:'🏨' },
  talat:{ th:'ตลาด', rom:'tà-làat', fr:'marché', en:'market', emoji:'🏪' },
  hongnam:{ th:'ห้องน้ำ', rom:'hɔ̂ɔng-náam', fr:'toilettes', en:'toilet', emoji:'🚻' },
  ranahan:{ th:'ร้านอาหาร', rom:'ráan-aa-hǎan', fr:'restaurant', en:'restaurant', emoji:'🍽️' },
  rongrian:{ th:'โรงเรียน', rom:'roong-rian', fr:'école', en:'school', emoji:'🏫' },
  rongphaya:{ th:'โรงพยาบาล', rom:'roong-phá-yaa-baan', fr:'hôpital', en:'hospital', emoji:'🏥' },
  sanambin:{ th:'สนามบิน', rom:'sà-nǎam-bin', fr:'aéroport', en:'airport', emoji:'🛫' },
  thanon:{ th:'ถนน', rom:'thà-nǒn', fr:'rue', en:'street', emoji:'🛣️' },
  thinai:{ th:'ที่ไหน', rom:'thîi-nǎi', fr:'où', en:'where', emoji:'🗺️' },
  sai:{ th:'ซ้าย', rom:'sáai', fr:'gauche', en:'left', emoji:'⬅️' },
  khwa:{ th:'ขวา', rom:'khwǎa', fr:'droite', en:'right', emoji:'➡️' },
  trong_pai:{ th:'ตรงไป', rom:'trong-pai', fr:'tout droit', en:'straight ahead', emoji:'⬆️' },
  klai:{ th:'ไกล', rom:'klai', fr:'loin', en:'far', emoji:'🏔️' },
  klai_near:{ th:'ใกล้', rom:'klâi', fr:'près', en:'near', emoji:'📍' },

  /* — animaux et objets — */
  ma_dog:{ th:'หมา', rom:'mǎa', fr:'chien', en:'dog', emoji:'🐶' },
  maeo:{ th:'แมว', rom:'mɛɛo', fr:'chat', en:'cat', emoji:'🐱' },
  chang:{ th:'ช้าง', rom:'cháang', fr:'éléphant', en:'elephant', emoji:'🐘' },
  nok:{ th:'นก', rom:'nók', fr:'oiseau', en:'bird', emoji:'🐦' },
  ngoen:{ th:'เงิน', rom:'ngəən', fr:'argent', en:'money', emoji:'💵' },
  thorasap:{ th:'โทรศัพท์', rom:'thoo-rá-sàp', fr:'téléphone', en:'phone', emoji:'📱' },
  nangsue:{ th:'หนังสือ', rom:'nǎng-sʉ̌ʉ', fr:'livre', en:'book', emoji:'📕' },
  krapao:{ th:'กระเป๋า', rom:'krà-pǎo', fr:'sac', en:'bag', emoji:'👜' },
  rom_umbrella:{ th:'ร่ม', rom:'rôm', fr:'parapluie', en:'umbrella', emoji:'☂️' },
  kaoi:{ th:'เก้าอี้', rom:'kâo-îi', fr:'chaise', en:'chair', emoji:'🪑' },
  to_table:{ th:'โต๊ะ', rom:'tó', fr:'table', en:'table', emoji:'🪑' },
  pratu:{ th:'ประตู', rom:'prà-tuu', fr:'porte', en:'door', emoji:'🚪' },

  /* — mots interrogatifs et outils — */
  khrai:{ th:'ใคร', rom:'khrai', fr:'qui', en:'who', emoji:'🕵️' },
  thammai:{ th:'ทำไม', rom:'tham-mai', fr:'pourquoi', en:'why', emoji:'🤔' },
  muearai:{ th:'เมื่อไหร่', rom:'mûea-rài', fr:'quand', en:'when', emoji:'📆' },
  yangngai:{ th:'ยังไง', rom:'yang-ngai', fr:'comment', en:'how', emoji:'⚙️' },
  phasa:{ th:'ภาษา', rom:'phaa-sǎa', fr:'langue', en:'language', emoji:'🗣️' },
  thai:{ th:'ไทย', rom:'thai', fr:'thaï', en:'Thai', emoji:'🇹🇭' },
  farangset:{ th:'ฝรั่งเศส', rom:'fà-ràng-sèet', fr:'français (pays)', en:'French (country)', emoji:'🇫🇷' },
  angkrit:{ th:'อังกฤษ', rom:'ang-krìt', fr:'anglais', en:'English', emoji:'🇬🇧' },
  tamruat:{ th:'ตำรวจ', rom:'tam-rùat', fr:'police', en:'police', emoji:'👮' },

  /* — classificateurs — */
  cl_tua:{ th:'ตัว', rom:'tua', fr:'classif. animaux/vêtements', en:'classifier: animals/clothes', emoji:'🐕' },
  cl_an:{ th:'อัน', rom:'an', fr:'classif. petits objets', en:'classifier: small objects', emoji:'🔧' },
  cl_bai:{ th:'ใบ', rom:'bai', fr:'classif. feuilles/récipients', en:'classifier: leaves/containers', emoji:'🍃' },
  cl_khuat:{ th:'ขวด', rom:'khùat', fr:'classif. bouteilles', en:'classifier: bottles', emoji:'🍾' },
  cl_cham:{ th:'ชาม', rom:'chaam', fr:'classif. bols', en:'classifier: bowls', emoji:'🥣' },
  cl_khan:{ th:'คัน', rom:'khan', fr:'classif. véhicules', en:'classifier: vehicles', emoji:'🚗' },
  cl_lem:{ th:'เล่ม', rom:'lêm', fr:'classif. livres', en:'classifier: books', emoji:'📕' }
  }
});

/* — phrases du palier A1 — */
ajouterPalier({ palier:'a1', phrases:{
  s_hello:{ chunks:['สวัสดี','ครับ'], rom:'sà-wàt-dii khráp', fr:'Bonjour (dit par un homme)', en:'Hello (said by a man)' },
  s_hello_f:{ chunks:['สวัสดี','ค่ะ'], rom:'sà-wàt-dii khâ', fr:'Bonjour (dit par une femme)', en:'Hello (said by a woman)' },
  s_hru:{ chunks:['สบายดี','ไหม'], rom:'sà-baai-dii mǎi', fr:'Comment ça va ?', en:'How are you?' },
  s_fine:{ chunks:['สบายดี','ค่ะ'], rom:'sà-baai-dii khâ', fr:'Ça va bien', en:'I’m fine' },
  s_thanks:{ chunks:['ขอบคุณ','มาก'], rom:'khɔ̀ɔp-khun mâak', fr:'Merci beaucoup', en:'Thank you very much' },
  s_sorry:{ chunks:['ขอโทษ','ครับ'], rom:'khɔ̌ɔ-thôot khráp', fr:'Excusez-moi', en:'Excuse me' },
  s_nevermind:{ chunks:['ไม่เป็นไร'], rom:'mâi-pen-rai', fr:'Ce n’est rien', en:'It’s nothing' },
  s_myname:{ chunks:['ผม','ชื่อ','ปิแอร์'], rom:'phǒm chûue Pierre', fr:'Je m’appelle Pierre', en:'My name is Pierre' },
  s_whatname:{ chunks:['คุณ','ชื่อ','อะไร'], rom:'khun chûue à-rai', fr:'Comment tu t’appelles ?', en:'What is your name?' },
  s_nicetomeet:{ chunks:['ยินดี','ที่','ได้','รู้จัก'], rom:'yin-dii thîi dâi rúu-jàk', fr:'Enchanté de te connaître', en:'Nice to meet you' },
  s_iam_french:{ chunks:['ผม','เป็น','คน','ฝรั่งเศส'], rom:'phǒm pen khon fà-ràng-sèet', fr:'Je suis français', en:'I am French' },
  s_wherefrom:{ chunks:['คุณ','มา','จาก','ไหน'], rom:'khun maa jàak nǎi', fr:'D’où viens-tu ?', en:'Where do you come from?' },
  s_fromfr:{ chunks:['ผม','มา','จาก','ฝรั่งเศส'], rom:'phǒm maa jàak fà-ràng-sèet', fr:'Je viens de France', en:'I come from France' },
  s_ieat:{ chunks:['ผม','กิน','ข้าว'], rom:'phǒm kin khâao', fr:'Je mange du riz', en:'I eat rice' },
  s_idrink:{ chunks:['ฉัน','ดื่ม','กาแฟ'], rom:'chǎn dùuem kaa-fɛɛ', fr:'Je bois du café', en:'I drink coffee' },
  s_youlike:{ chunks:['คุณ','ชอบ','อาหาร','ไทย','ไหม'], rom:'khun chɔ̂ɔp aa-hǎan thai mǎi', fr:'Tu aimes la cuisine thaïe ?', en:'Do you like Thai food?' },
  s_notspicy:{ chunks:['ไม่','เผ็ด'], rom:'mâi phèt', fr:'Pas épicé', en:'Not spicy' },
  s_verygood:{ chunks:['อร่อย','มาก'], rom:'à-rɔ̀i mâak', fr:'C’est très bon', en:'It’s very good' },
  s_water:{ chunks:['ขอ','น้ำ','หนึ่ง','ขวด'], rom:'khɔ̌ɔ náam nùeng khùat', fr:'Une bouteille d’eau, s’il vous plaît', en:'One bottle of water, please' },
  s_noodle:{ chunks:['ขอ','ก๋วยเตี๋ยว','หนึ่ง','ชาม'], rom:'khɔ̌ɔ kǔai-tǐao nùeng chaam', fr:'Un bol de nouilles, s’il vous plaît', en:'One bowl of noodles, please' },
  s_beer:{ chunks:['ขอ','เบียร์','เย็น'], rom:'khɔ̌ɔ bia yen', fr:'Une bière fraîche, s’il vous plaît', en:'A cold beer, please' },
  s_hungry:{ chunks:['ผม','หิว','มาก'], rom:'phǒm hǐu mâak', fr:'J’ai très faim', en:'I am very hungry' },
  s_full:{ chunks:['อิ่ม','แล้ว'], rom:'ìm lɛ́ɛo', fr:'Je n’ai plus faim', en:'I’m full' },
  s_howmuch:{ chunks:['เท่าไหร่'], rom:'thâo-rài', fr:'Combien ?', en:'How much?' },
  s_price:{ chunks:['ห้า','สิบ','บาท'], rom:'hâa sìp bàat', fr:'Cinquante bahts', en:'Fifty baht' },
  s_expensive:{ chunks:['แพง','เกินไป'], rom:'phɛɛng kəən-pai', fr:'C’est trop cher', en:'That’s too expensive' },
  s_cheaper:{ chunks:['ลด','ได้','ไหม'], rom:'lót dâi mǎi', fr:'Vous pouvez baisser le prix ?', en:'Can you lower the price?' },
  s_toilet:{ chunks:['ห้องน้ำ','อยู่','ที่ไหน'], rom:'hɔ̂ɔng-náam yùu thîi-nǎi', fr:'Où sont les toilettes ?', en:'Where is the toilet?' },
  s_hospital:{ chunks:['โรงพยาบาล','อยู่','ที่ไหน'], rom:'roong-phá-yaa-baan yùu thîi-nǎi', fr:'Où est l’hôpital ?', en:'Where is the hospital?' },
  s_gohotel:{ chunks:['ไป','โรงแรม'], rom:'pai roong-rɛɛm', fr:'Aller à l’hôtel', en:'Go to the hotel' },
  s_turnleft:{ chunks:['เลี้ยว','ซ้าย'], rom:'líao sáai', fr:'Tourner à gauche', en:'Turn left' },
  s_turnright:{ chunks:['เลี้ยว','ขวา'], rom:'líao khwǎa', fr:'Tourner à droite', en:'Turn right' },
  s_straight:{ chunks:['ตรงไป'], rom:'trong-pai', fr:'Tout droit', en:'Straight ahead' },
  s_gomarket:{ chunks:['เรา','ไป','ตลาด'], rom:'rao pai tà-làat', fr:'Nous allons au marché', en:'We are going to the market' },
  s_tomorrow:{ chunks:['พรุ่งนี้','ผม','ไป','ตลาด'], rom:'phrûng-níi phǒm pai tà-làat', fr:'Demain je vais au marché', en:'Tomorrow I’m going to the market' },
  s_ihave:{ chunks:['ผม','มี','เพื่อน','คน','ไทย'], rom:'phǒm mii phûean khon thai', fr:'J’ai un ami thaïlandais', en:'I have a Thai friend' },
  s_ispeak:{ chunks:['ผม','พูด','ไทย','นิดหน่อย'], rom:'phǒm phûut thai nít-nɔ̀i', fr:'Je parle un peu thaï', en:'I speak a little Thai' },
  s_notunderstand:{ chunks:['ผม','ไม่','เข้าใจ'], rom:'phǒm mâi khâo-jai', fr:'Je ne comprends pas', en:'I don’t understand' },
  s_speakslow:{ chunks:['พูด','ช้า','ๆ','ได้','ไหม'], rom:'phûut cháa cháa dâi mǎi', fr:'Pouvez-vous parler lentement ?', en:'Could you speak slowly?' },
  s_ilove:{ chunks:['ฉัน','รัก','เมืองไทย'], rom:'chǎn rák mueang-thai', fr:'J’aime la Thaïlande', en:'I love Thailand' },
  s_study:{ chunks:['ผม','เรียน','ภาษา','ไทย'], rom:'phǒm rian phaa-sǎa thai', fr:'J’étudie la langue thaïe', en:'I study Thai' },
  s_pretty:{ chunks:['ภาษา','ไทย','สวย','มาก'], rom:'phaa-sǎa thai sǔai mâak', fr:'La langue thaïe est très belle', en:'Thai is a very beautiful language' },
  s_twodogs:{ chunks:['ผม','มี','หมา','สอง','ตัว'], rom:'phǒm mii mǎa sɔ̌ɔng tua', fr:'J’ai deux chiens', en:'I have two dogs' },
  s_threefr:{ chunks:['เพื่อน','สาม','คน'], rom:'phûean sǎam khon', fr:'Trois amis', en:'Three friends' },
  s_twocars:{ chunks:['รถ','สอง','คัน'], rom:'rót sɔ̌ɔng khan', fr:'Deux voitures', en:'Two cars' },
  s_family:{ chunks:['ผม','มี','พี่','สอง','คน'], rom:'phǒm mii phîi sɔ̌ɔng khon', fr:'J’ai deux grands frères', en:'I have two older brothers' },
  s_mother:{ chunks:['แม่','ทำงาน','ตอนเช้า'], rom:'mɛ̂ɛ tham-ngaan tɔɔn-cháao', fr:'Maman travaille le matin', en:'Mum works in the morning' },
  s_hot:{ chunks:['วันนี้','ร้อน','มาก'], rom:'wan-níi rɔ́ɔn mâak', fr:'Aujourd’hui il fait très chaud', en:'It is very hot today' },
  s_sleep:{ chunks:['ผม','อยาก','นอน'], rom:'phǒm yàak nɔɔn', fr:'Je veux dormir', en:'I want to sleep' },
  s_help:{ chunks:['ช่วย','ผม','หน่อย'], rom:'chûai phǒm nɔ̀i', fr:'Aidez-moi, s’il vous plaît', en:'Please help me' },
  s_wait:{ chunks:['รอ','สัก','ครู่'], rom:'rɔɔ sàk khrûu', fr:'Attendez un instant', en:'Wait a moment' },
  s_where_go:{ chunks:['คุณ','ไป','ไหน'], rom:'khun pai nǎi', fr:'Où vas-tu ?', en:'Where are you going?' },
  s_book_red:{ chunks:['หนังสือ','สีแดง'], rom:'nǎng-sʉ̌ʉ sǐi-dɛɛng', fr:'Le livre rouge', en:'The red book' },
  s_big_house:{ chunks:['บ้าน','ใหญ่'], rom:'bâan yài', fr:'Une grande maison', en:'A big house' },
  s_buy_fruit:{ chunks:['ผม','ซื้อ','ผลไม้'], rom:'phǒm súue phǒn-lá-máai', fr:'J’achète des fruits', en:'I buy fruit' },
  s_no_money:{ chunks:['ผม','ไม่','มี','เงิน'], rom:'phǒm mâi mii ngəən', fr:'Je n’ai pas d’argent', en:'I have no money' },
  s_read_book:{ chunks:['เขา','อ่าน','หนังสือ'], rom:'khǎo àan nǎng-sʉ̌ʉ', fr:'Il lit un livre', en:'He reads a book' },
  s_go_school:{ chunks:['เด็ก','ไป','โรงเรียน'], rom:'dèk pai roong-rian', fr:'L’enfant va à l’école', en:'The child goes to school' },
  s_taxi_airport:{ chunks:['ไป','สนามบิน','ครับ'], rom:'pai sà-nǎam-bin khráp', fr:'À l’aéroport, s’il vous plaît', en:'To the airport, please' }
}});

/* — alphabet et tons (parcours d'écriture) — */
ajouterPalier({ palier:'a1',
  romanisations:{
    'ไหม':'mǎi','ปิแอร์':'pi-ɛɛ','ขอ':'khɔ̌ɔ','เลี้ยว':'líao','เมืองไทย':'mueang-thai',
    'เกินไป':'kəən-pai','จาก':'jàak','ไหน':'nǎi','หน่อย':'nɔ̀i','แล้ว':'lɛ́ɛo','ลด':'lót',
    'ได้':'dâi','ที่':'thîi','รู้จัก':'rúu-jàk','สัก':'sàk','ครู่':'khrûu','ๆ':'(répétition)'
  },
  alphabet:[
  { th:'ก', rom:'k',  fr:'ko kai — poulet', en:'ko kai — chicken', cls:'moyenne', emoji:'🐔' },
  { th:'ข', rom:'kh', fr:'kho khai — œuf', en:'kho khai — egg', cls:'haute', emoji:'🥚' },
  { th:'ค', rom:'kh', fr:'kho khwai — buffle', en:'kho khwai — buffalo', cls:'basse', emoji:'🐃' },
  { th:'ฆ', rom:'kh', fr:'kho rakhang — cloche', en:'kho rakhang — bell', cls:'basse', emoji:'🔔' },
  { th:'ง', rom:'ng', fr:'ngo ngu — serpent', en:'ngo ngu — snake', cls:'basse', emoji:'🐍' },
  { th:'จ', rom:'j',  fr:'jo jan — assiette', en:'jo jan — plate', cls:'moyenne', emoji:'🍽️' },
  { th:'ฉ', rom:'ch', fr:'cho ching — cymbales', en:'cho ching — cymbals', cls:'haute', emoji:'🎶' },
  { th:'ช', rom:'ch', fr:'cho chang — éléphant', en:'cho chang — elephant', cls:'basse', emoji:'🐘' },
  { th:'ซ', rom:'s',  fr:'so so — chaîne', en:'so so — chain', cls:'basse', emoji:'⛓️' },
  { th:'ฌ', rom:'ch', fr:'cho choe — arbre', en:'cho choe — tree', cls:'basse', emoji:'🌳' },
  { th:'ญ', rom:'y',  fr:'yo ying — femme', en:'yo ying — woman', cls:'basse', emoji:'👩' },
  { th:'ฎ', rom:'d',  fr:'do chada — diadème', en:'do chada — headdress', cls:'moyenne', emoji:'👑' },
  { th:'ฏ', rom:'t',  fr:'to patak — aiguillon', en:'to patak — goad', cls:'moyenne', emoji:'🔱' },
  { th:'ฐ', rom:'th', fr:'tho than — socle', en:'tho than — pedestal', cls:'haute', emoji:'🗿' },
  { th:'ฑ', rom:'th', fr:'tho montho — Montho', en:'tho montho — Montho', cls:'basse', emoji:'👸' },
  { th:'ฒ', rom:'th', fr:'tho phu thao — vieillard', en:'tho phu thao — elder', cls:'basse', emoji:'👴' },
  { th:'ณ', rom:'n',  fr:'no nen — novice', en:'no nen — novice monk', cls:'basse', emoji:'🧘' },
  { th:'ด', rom:'d',  fr:'do dek — enfant', en:'do dek — child', cls:'moyenne', emoji:'🧒' },
  { th:'ต', rom:'t',  fr:'to tao — tortue', en:'to tao — turtle', cls:'moyenne', emoji:'🐢' },
  { th:'ถ', rom:'th', fr:'tho thung — sac', en:'tho thung — sack', cls:'haute', emoji:'👜' },
  { th:'ท', rom:'th', fr:'tho thahan — soldat', en:'tho thahan — soldier', cls:'basse', emoji:'💂' },
  { th:'ธ', rom:'th', fr:'tho thong — drapeau', en:'tho thong — flag', cls:'basse', emoji:'🚩' },
  { th:'น', rom:'n',  fr:'no nu — souris', en:'no nu — mouse', cls:'basse', emoji:'🐭' },
  { th:'บ', rom:'b',  fr:'bo baimai — feuille', en:'bo baimai — leaf', cls:'moyenne', emoji:'🍃' },
  { th:'ป', rom:'p',  fr:'po pla — poisson', en:'po pla — fish', cls:'moyenne', emoji:'🐟' },
  { th:'ผ', rom:'ph', fr:'pho phueng — abeille', en:'pho phueng — bee', cls:'haute', emoji:'🐝' },
  { th:'ฝ', rom:'f',  fr:'fo fa — couvercle', en:'fo fa — lid', cls:'haute', emoji:'🥫' },
  { th:'พ', rom:'ph', fr:'pho phan — plateau', en:'pho phan — tray', cls:'basse', emoji:'🍶' },
  { th:'ฟ', rom:'f',  fr:'fo fan — dent', en:'fo fan — tooth', cls:'basse', emoji:'🦷' },
  { th:'ภ', rom:'ph', fr:'pho samphao — voilier', en:'pho samphao — sailboat', cls:'basse', emoji:'⛵' },
  { th:'ม', rom:'m',  fr:'mo ma — cheval', en:'mo ma — horse', cls:'basse', emoji:'🐴' },
  { th:'ย', rom:'y',  fr:'yo yak — géant', en:'yo yak — giant', cls:'basse', emoji:'👹' },
  { th:'ร', rom:'r',  fr:'ro ruea — bateau', en:'ro ruea — boat', cls:'basse', emoji:'🚣' },
  { th:'ล', rom:'l',  fr:'lo ling — singe', en:'lo ling — monkey', cls:'basse', emoji:'🐒' },
  { th:'ว', rom:'w',  fr:'wo waen — bague', en:'wo waen — ring', cls:'basse', emoji:'💍' },
  { th:'ศ', rom:'s',  fr:'so sala — pavillon', en:'so sala — pavilion', cls:'haute', emoji:'⛩️' },
  { th:'ษ', rom:'s',  fr:'so ruesi — ermite', en:'so ruesi — hermit', cls:'haute', emoji:'🧙' },
  { th:'ส', rom:'s',  fr:'so suea — tigre', en:'so suea — tiger', cls:'haute', emoji:'🐯' },
  { th:'ห', rom:'h',  fr:'ho hip — coffre', en:'ho hip — chest', cls:'haute', emoji:'📦' },
  { th:'ฬ', rom:'l',  fr:'lo chula — cerf-volant', en:'lo chula — kite', cls:'basse', emoji:'🪁' },
  { th:'อ', rom:'o',  fr:'o ang — bassine', en:'o ang — basin', cls:'moyenne', emoji:'🪣' },
  { th:'ฮ', rom:'h',  fr:'ho nokhuk — hibou', en:'ho nokhuk — owl', cls:'basse', emoji:'🦉' },
  { th:'ฃ', rom:'kh', fr:'kho khuat — bouteille (désuet)', en:'kho khuat — bottle (obsolete)', cls:'haute', emoji:'🍾' },
  { th:'ฅ', rom:'kh', fr:'kho khon — personne (désuet)', en:'kho khon — person (obsolete)', cls:'basse', emoji:'🧍' },
  { th:'-า', rom:'aa', fr:'voyelle longue « aa »', en:'long vowel “aa”', emoji:'🅰️' },
  { th:'-ิ', rom:'i',  fr:'voyelle brève « i »', en:'short vowel “i”', emoji:'🇮' },
  { th:'-ี', rom:'ii', fr:'voyelle longue « ii »', en:'long vowel “ii”', emoji:'🇮' },
  { th:'-ุ', rom:'u',  fr:'voyelle brève « ou »', en:'short vowel “u”', emoji:'🇺' },
  { th:'-ู', rom:'uu', fr:'voyelle longue « ouu »', en:'long vowel “uu”', emoji:'🇺' },
  { th:'เ-', rom:'ee', fr:'voyelle « éé » (devant)', en:'vowel “ee” (written first)', emoji:'🅴' },
  { th:'แ-', rom:'ɛɛ', fr:'voyelle « èè » (devant)', en:'vowel “ae” (written first)', emoji:'🅴' },
  { th:'โ-', rom:'oo', fr:'voyelle « oo » (devant)', en:'vowel “oo” (written first)', emoji:'🅾️' },
  { th:'ไ-', rom:'ai', fr:'voyelle « ai » (devant)', en:'vowel “ai” (written first)', emoji:'🆎' },
  { th:'-ำ', rom:'am', fr:'voyelle « am »', en:'vowel “am”', emoji:'🅰️' },
  { th:'-่', rom:'ton bas', fr:'mái èek — 1er signe de ton', en:'mái èek — first tone mark', emoji:'⬇️' },
  { th:'-้', rom:'ton descendant', fr:'mái thoo — 2e signe de ton', en:'mái thoo — second tone mark', emoji:'↘️' },
  { th:'-๊', rom:'ton haut', fr:'mái trii — 3e signe de ton', en:'mái trii — third tone mark', emoji:'⬆️' },
  { th:'-๋', rom:'ton montant', fr:'mái jàt-tà-waa — 4e signe', en:'mái jàt-tà-waa — fourth tone mark', emoji:'↗️' }
  ],
  tons:[
  { th:'กา', rom:'kaa', ton:'moyen', tonEn:'mid', regle:{fr:'consonne moyenne (ก) + syllabe vivante, sans signe → ton moyen', en:'mid consonant (ก) + live syllable, no mark → mid tone'} },
  { th:'ขา', rom:'khǎa', ton:'montant', tonEn:'rising', regle:{fr:'consonne haute (ข) + syllabe vivante, sans signe → ton montant', en:'high consonant (ข) + live syllable, no mark → rising tone'} },
  { th:'คา', rom:'khaa', ton:'moyen', tonEn:'mid', regle:{fr:'consonne basse (ค) + syllabe vivante, sans signe → ton moyen', en:'low consonant (ค) + live syllable, no mark → mid tone'} },
  { th:'ก่า', rom:'kàa', ton:'bas', tonEn:'low', regle:{fr:'consonne moyenne + mái èek → ton bas', en:'mid consonant + mái èek → low tone'} },
  { th:'ข่า', rom:'khàa', ton:'bas', tonEn:'low', regle:{fr:'consonne haute + mái èek → ton bas', en:'high consonant + mái èek → low tone'} },
  { th:'ค่า', rom:'khâa', ton:'descendant', tonEn:'falling', regle:{fr:'consonne basse + mái èek → ton descendant', en:'low consonant + mái èek → falling tone'} },
  { th:'ก้า', rom:'kâa', ton:'descendant', tonEn:'falling', regle:{fr:'consonne moyenne + mái thoo → ton descendant', en:'mid consonant + mái thoo → falling tone'} },
  { th:'ข้า', rom:'khâa', ton:'descendant', tonEn:'falling', regle:{fr:'consonne haute + mái thoo → ton descendant', en:'high consonant + mái thoo → falling tone'} },
  { th:'ค้า', rom:'kháa', ton:'haut', tonEn:'high', regle:{fr:'consonne basse + mái thoo → ton haut', en:'low consonant + mái thoo → high tone'} },
  { th:'ก๊า', rom:'káa', ton:'haut', tonEn:'high', regle:{fr:'consonne moyenne + mái trii → ton haut', en:'mid consonant + mái trii → high tone'} },
  { th:'ก๋า', rom:'kǎa', ton:'montant', tonEn:'rising', regle:{fr:'consonne moyenne + mái jàt-tà-waa → ton montant', en:'mid consonant + mái jàt-tà-waa → rising tone'} }
  ]
});

/* — parcours du palier A1 — */
ajouterPalier({ palier:'a1',
  sections:[
    { id:'sec-a1', titre:{fr:'Débutant', en:'Beginner'},
      sousTitre:{fr:'Se faire comprendre au quotidien', en:'Getting by day to day'},
      unites:['a1u1','a1u2','a1u3','a1u4','a1u5','a1u6','a1u7','a1u8','a1u9','a1u10','a1u11','a1u12'],
      couleur:'#58CC02' }
  ],
  unites:[
  { id:'a1u1', title:{fr:'Salutations', en:'Greetings'}, subtitle:{fr:'Dire bonjour et merci', en:'Saying hello and thank you'},
    color:'#58CC02', icon:'👋', lessons:[
    { id:'a1u1l1', title:{fr:'Bonjour', en:'Hello'}, words:['sawatdee','khrap','kha','khopkhun'], sentences:['s_hello','s_hello_f','s_thanks'] },
    { id:'a1u1l2', title:{fr:'Ça va ?', en:'How are you?'}, words:['sabaidee','chai','mai_no','khothot'], sentences:['s_hru','s_fine','s_sorry'] },
    { id:'a1u1l3', title:{fr:'Politesse', en:'Being polite'}, words:['maipenrai','lakon','chok_dee','phop_kan','raatri','yindee'], sentences:['s_nevermind','s_thanks','s_nicetomeet'] }
  ]},
  { id:'a1u2', title:{fr:'Se présenter', en:'Introducing yourself'}, subtitle:{fr:'Qui es-tu ?', en:'Who are you?'},
    color:'#1CB0F6', icon:'🧑', lessons:[
    { id:'a1u2l1', title:{fr:'Pronoms', en:'Pronouns'}, words:['phom','chan','khun','khao','rao','phuak_khao'], sentences:['s_myname','s_whatname'] },
    { id:'a1u2l2', title:{fr:'Les gens', en:'People'}, words:['khon','phuean','khru','nakrian','phuchai','phuying','dek'], sentences:['s_ihave','s_go_school'] },
    { id:'a1u2l3', title:{fr:'D’où viens-tu ?', en:'Where from?'}, words:['cheu','arai','thai','farangset','angkrit','phasa'], sentences:['s_wherefrom','s_fromfr','s_iam_french','s_nicetomeet'] },
    { id:'a1u2l4', title:{fr:'Poser une question', en:'Asking a question'}, words:['khrai','thammai','muearai','yangngai','thinai','arai'], sentences:['s_whatname','s_where_go','s_wherefrom'] }
  ]},
  { id:'a1u3', title:{fr:'Les nombres', en:'Numbers'}, subtitle:{fr:'Compter et payer', en:'Counting and paying'},
    color:'#FF4B4B', icon:'🔢', lessons:[
    { id:'a1u3l1', title:{fr:'0 à 5', en:'0 to 5'}, words:['sun','nueng','song','sam','si','ha'], sentences:['s_twodogs','s_threefr'] },
    { id:'a1u3l2', title:{fr:'6 à 20', en:'6 to 20'}, words:['hok','jet','paet','kao','sip','sip_et','yisip'], sentences:['s_price'] },
    { id:'a1u3l3', title:{fr:'Prix', en:'Prices'}, words:['roi','phan','baht','thaorai','ki','ngoen'], sentences:['s_howmuch','s_price','s_expensive','s_no_money'] }
  ]},
  { id:'a1u4', title:{fr:'Manger', en:'Eating'}, subtitle:{fr:'À table', en:'At the table'},
    color:'#FF9600', icon:'🍚', lessons:[
    { id:'a1u4l1', title:{fr:'Les bases', en:'Basics'}, words:['kin','duem','nam','khao_rice','kafae','cha'], sentences:['s_ieat','s_idrink'] },
    { id:'a1u4l2', title:{fr:'Viandes', en:'Meats'}, words:['kai','mu','nuea','pla','kung','khai'], sentences:['s_youlike'] },
    { id:'a1u4l3', title:{fr:'Goûts', en:'Tastes'}, words:['phet','aroi','wan','priao','khem','phak'], sentences:['s_notspicy','s_verygood'] }
  ]},
  { id:'a1u5', title:{fr:'Au restaurant', en:'At the restaurant'}, subtitle:{fr:'Commander', en:'Ordering'},
    color:'#FFB020', icon:'🍜', lessons:[
    { id:'a1u5l1', title:{fr:'Plats', en:'Dishes'}, words:['kuaitiao','phatthai','somtam','ahan','ranahan'], sentences:['s_noodle','s_verygood'] },
    { id:'a1u5l2', title:{fr:'Boissons', en:'Drinks'}, words:['bia','namkhaeng','nom','namtan','kluea','khanom'], sentences:['s_water','s_beer'] },
    { id:'a1u5l3', title:{fr:'Faim et soif', en:'Hungry and thirsty'}, words:['hiu','im','ao','yak','phonlamai'], sentences:['s_hungry','s_full','s_buy_fruit'] }
  ]},
  { id:'a1u6', title:{fr:'La famille', en:'Family'}, subtitle:{fr:'Les proches', en:'Close relatives'},
    color:'#FF86D0', icon:'👨‍👩‍👧', lessons:[
    { id:'a1u6l1', title:{fr:'Parents', en:'Parents'}, words:['mae','pho','luk','khropkhrua'], sentences:['s_mother','s_family'] },
    { id:'a1u6l2', title:{fr:'Frères et sœurs', en:'Siblings'}, words:['phi','nong','sami','phanraya'], sentences:['s_family'] },
    { id:'a1u6l3', title:{fr:'Grands-parents', en:'Grandparents'}, words:['pu','ya','ta','yai'], sentences:['s_ihave'] }
  ]},
  { id:'a1u7', title:{fr:'Décrire', en:'Describing'}, subtitle:{fr:'Couleurs et qualités', en:'Colours and qualities'},
    color:'#CE82FF', icon:'🎨', lessons:[
    { id:'a1u7l1', title:{fr:'Couleurs', en:'Colours'}, words:['si_daeng','si_namngen','si_khiao','si_dam','si_khao','si_lueang','si_som'], sentences:['s_book_red'] },
    { id:'a1u7l2', title:{fr:'Tailles', en:'Sizes'}, words:['yai','lek','mai_new','kao_old','reo','cha_slow'], sentences:['s_big_house'] },
    { id:'a1u7l3', title:{fr:'Jugements', en:'Judgements'}, words:['di','mai_di','suai','phaeng','thuk','mak','nitnoi'], sentences:['s_pretty','s_expensive'] }
  ]},
  { id:'a1u8', title:{fr:'Le temps', en:'Time'}, subtitle:{fr:'Quand ?', en:'When?'},
    color:'#00CD9C', icon:'⏰', lessons:[
    { id:'a1u8l1', title:{fr:'Aujourd’hui', en:'Today'}, words:['wanni','phrungni','mueawan','diao_ni'], sentences:['s_tomorrow','s_hot'] },
    { id:'a1u8l4', title:{fr:'Le temps qu’il fait', en:'Weather'}, words:['ron','yen','nao','rom_umbrella'], sentences:['s_hot'] },
    { id:'a1u8l2', title:{fr:'Moments', en:'Times of day'}, words:['tonchao','tonbai','tonyen','klangkhuen'], sentences:['s_mother'] },
    { id:'a1u8l3', title:{fr:'Durées', en:'Durations'}, words:['wela','wan_day','athit','duean','pi','chaomong'], sentences:['s_wait'] }
  ]},
  { id:'a1u9', title:{fr:'Se déplacer', en:'Getting around'}, subtitle:{fr:'Transports', en:'Transport'},
    color:'#1CB0F6', icon:'🚕', lessons:[
    { id:'a1u9l1', title:{fr:'Véhicules', en:'Vehicles'}, words:['rot','rotfai','rotmee','taxi','khrueangbin'], sentences:['s_taxi_airport','s_twocars'] },
    { id:'a1u9l2', title:{fr:'Aller, venir', en:'Coming and going'}, words:['pai','ma','doen','wing'], sentences:['s_gomarket','s_where_go'] },
    { id:'a1u9l3', title:{fr:'Directions', en:'Directions'}, words:['thinai','sai','khwa','trong_pai','klai','klai_near'], sentences:['s_turnleft','s_turnright','s_straight'] }
  ]},
  { id:'a1u10', title:{fr:'En ville', en:'Around town'}, subtitle:{fr:'Les lieux', en:'Places'},
    color:'#2CC3A5', icon:'🏙️', lessons:[
    { id:'a1u10l1', title:{fr:'Lieux', en:'Places'}, words:['ban','rongraem','talat','ranahan','rongrian'], sentences:['s_gohotel','s_gomarket'] },
    { id:'a1u10l2', title:{fr:'Où est… ?', en:'Where is…?'}, words:['hongnam','rongphaya','sanambin','thanon','yu'], sentences:['s_toilet','s_hospital'] },
    { id:'a1u10l3', title:{fr:'Urgences', en:'Emergencies'}, words:['chuai','tamruat','ro','thorasap'], sentences:['s_help','s_wait'] },
    { id:'a1u10l4', title:{fr:'Dans la maison', en:'Inside the house'}, words:['kaoi','to_table','pratu','ban'], sentences:['s_big_house'] }
  ]},
  { id:'a1u11', title:{fr:'Au quotidien', en:'Everyday life'}, subtitle:{fr:'Les verbes utiles', en:'Useful verbs'},
    color:'#A560E8', icon:'🔁', lessons:[
    { id:'a1u11l1', title:{fr:'Aimer, avoir', en:'Liking, having'}, words:['chop','rak','mi','pen','ru'], sentences:['s_ilove','s_ihave'] },
    { id:'a1u11l2', title:{fr:'Apprendre', en:'Learning'}, words:['rian','an','khian','fang','phut','khaochai'], sentences:['s_study','s_ispeak','s_notunderstand','s_speakslow'] },
    { id:'a1u11l3', title:{fr:'Journée', en:'Daily routine'}, words:['tham','du','non','thamngan','nang','yuen'], sentences:['s_sleep','s_read_book'] }
  ]},
  { id:'a1u12', title:{fr:'Compter les choses', en:'Counting things'}, subtitle:{fr:'Les classificateurs', en:'Classifiers'},
    color:'#7B61FF', icon:'🧮', lessons:[
    { id:'a1u12l1', title:{fr:'Êtres vivants', en:'Living beings'}, words:['cl_tua','khon','ma_dog','maeo','chang','nok'], sentences:['s_twodogs','s_threefr'] },
    { id:'a1u12l2', title:{fr:'Objets', en:'Objects'}, words:['cl_an','cl_bai','cl_khuat','cl_lem','nangsue','krapao'], sentences:['s_water'] },
    { id:'a1u12l3', title:{fr:'Achats', en:'Shopping'}, words:['cl_khan','cl_cham','sue','khai_sell','hai'], sentences:['s_noodle','s_twocars','s_buy_fruit'] }
  ]},

  /* parcours d'écriture */
  { id:'a1w1', title:{fr:'Alphabet', en:'Alphabet'}, subtitle:{fr:'Les 44 consonnes et les voyelles', en:'The 44 consonants and the vowels'},
    color:'#CE82FF', icon:'🔤', script:true, ecriture:true, lessons:[
    { id:'a1w1l1', title:{fr:'Consonnes 1', en:'Consonants 1'}, script:[0,1,2,4,5] },
    { id:'a1w1l2', title:{fr:'Consonnes 2', en:'Consonants 2'}, script:[6,7,8,10,17] },
    { id:'a1w1l3', title:{fr:'Consonnes 3', en:'Consonants 3'}, script:[18,19,20,22,23] },
    { id:'a1w1l4', title:{fr:'Consonnes 4', en:'Consonants 4'}, script:[24,25,27,30,31] },
    { id:'a1w1l5', title:{fr:'Consonnes 5', en:'Consonants 5'}, script:[32,33,34,37,38] },
    { id:'a1w1l6', title:{fr:'Consonnes 6', en:'Consonants 6'}, script:[13,26,28,35,40,41] },
    { id:'a1w1l7', title:{fr:'Voyelles', en:'Vowels'}, script:[44,45,46,47,48,49,50,51,52,53] },
    { id:'a1w1l8', title:{fr:'Signes de ton', en:'Tone marks'}, script:[54,55,56,57] }
  ]},
  { id:'a1w2', title:{fr:'Les tons', en:'Tones'}, subtitle:{fr:'Lire le ton d’une syllabe', en:'Reading a syllable’s tone'},
    color:'#7B61FF', icon:'🎼', ecriture:true, lessons:[
    { id:'a1w2l1', title:{fr:'Règles de ton 1', en:'Tone rules 1'}, tones:[0,1,2,3,4] },
    { id:'a1w2l2', title:{fr:'Règles de ton 2', en:'Tone rules 2'}, tones:[5,6,7,8,9,10] }
  ]}
  ]
});
